Repository CESI-Pandev/pandasenp_flutter, pull requests merged in 2023-03, with the labels that each got.

#2 1 page daccueil
  directus-pandasenp/docker-compose.yml
  images/logo.png
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  lib/main.dart
  lib/pages/home.dart
  lib/pages/login.dart
  lib/pages/register.dart
  lib/pages/welcome.dart
  macos/Flutter/Flutter-Debug.xcconfig
  macos/Flutter/Flutter-Release.xcconfig
  macos/Podfile
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#6 4 login register backend
  lib/controllers/auth.dart
  lib/controllers/auth/login.dart
  lib/controllers/auth/register.dart
  lib/main.dart
  lib/model/user.dart
  lib/pages/app_base.dart
  lib/pages/home.dart
  lib/pages/login.dart
  lib/pages/profile.dart
  lib/pages/welcome.dart
  pubspec.yaml
Labels: enhancement

#8 Added ressource list
  lib/controllers/auth.dart
  lib/controllers/ressource.dart
  lib/extensions/date_time.dart
  lib/model/category.dart
  lib/model/comment.dart
  lib/model/ressource.dart
  lib/model/ressource_type.dart
  lib/model/status.dart
  lib/model/user.dart
  lib/pages/app_base.dart
  lib/pages/ressource_card.dart
  lib/pages/ressource_list.dart
  macos/Podfile.lock
  macos/Runner.xcodeproj/project.pbxproj
  macos/Runner.xcworkspace/contents.xcworkspacedata
  pubspec.lock
Labels: enhancement

#12 Conversation
  lib/controllers/auth.dart
  lib/controllers/message.dart
  lib/controllers/ressource.dart
  lib/controllers/user.dart
  lib/main.dart
  lib/model/message.dart
  lib/model/relation.dart
  lib/model/user.dart
  lib/pages/app_base.dart
  lib/pages/chat.dart
  lib/pages/conversation_list.dart
  lib/pages/login.dart
  lib/pages/profile.dart
  lib/pages/test.dart
  lib/widgets/user_tile.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: feature

#14 5 navigation refactor
  lib/controllers/ressource.dart
  lib/env.dart
  lib/pages/conversation_list.dart
  lib/pages/test.dart
  lib/view/pages/chat.dart
  lib/view/pages/conversation_list.dart
  lib/view/pages/home.dart
  lib/view/pages/login.dart
  lib/view/pages/profile.dart
  lib/view/pages/ressource_list.dart
  lib/view/pages/welcome.dart
  lib/view/widgets/app_base.dart
  lib/view/widgets/user_tile.dart
Labels: refactor
